import { 
  Camera, 
  Image, 
  CheckCircle, 
  AlertTriangle, 
  XCircle, 
  Shield, 
  Search, 
  History, 
  Settings, 
  ChevronLeft, 
  ChevronRight, 
  ChevronDown, 
  MoreHorizontal, 
  Share2, 
  Download, 
  Trash2, 
  Eye, 
  EyeOff, 
  Info, 
  AlertCircle, 
  Check, 
  X, 
  Loader2, 
  Zap, 
  Pill, 
  Box, 
  ScanLine, 
  RefreshCw, 
  RotateCcw, 
  Settings as SettingsIcon,
  Home,
  Clock,
  MapPin,
  WifiOff,
  Globe,
  Lock,
  Unlock,
  User,
  Users,
  FileText,
  BarChart2,
  Bell,
  Menu,
  Sun,
  Moon,
  Languages,
  HelpCircle,
  Flag,
  MessageSquare,
  Heart,
  Star,
  ArrowUpRight,
  ExternalLink,
  Copy,
  Edit,
  Plus,
  Minus,
  Filter,
  SortAsc,
  SortDesc,
  Calendar,
  Clock as ClockIcon,
  MapPin as MapPinIcon,
  ShieldCheck,
  ShieldAlert,
  ShieldX,
  Microscope,
  FlaskConical,
  Database,
  Cloud,
  CloudOff,
  Wifi,
  Signal,
  Battery,
  BatteryLow,
  Volume2,
  VolumeX,
  Vibrate,
  VibrateOff,
  Accessibility,
  Highlighter,
  Type,
  Image as ImageIcon,
  Camera as CameraIcon,
  Upload,
  Download as DownloadIcon,
  Trash,
  Edit2,
  Save,
  CheckCircle2,
  AlertTriangle as AlertTriangleIcon,
} from 'lucide-react';

export const Icons = {
  camera: Camera,
  image: Image,
  checkCircle: CheckCircle,
  alertTriangle: AlertTriangle,
  xCircle: XCircle,
  shield: Shield,
  search: Search,
  history: History,
  settings: Settings,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  moreHorizontal: MoreHorizontal,
  share: Share2,
  download: Download,
  trash: Trash2,
  eye: Eye,
  eyeOff: EyeOff,
  info: Info,
  alertCircle: AlertCircle,
  check: Check,
  x: X,
  loader: Loader2,
  zap: Zap,
  pill: Pill,
  box: Box,
  scanLine: ScanLine,
  refresh: RefreshCw,
  rotate: RotateCcw,
  settingsIcon: SettingsIcon,
  home: Home,
  clock: Clock,
  mapPin: MapPin,
  wifiOff: WifiOff,
  globe: Globe,
  lock: Lock,
  unlock: Unlock,
  user: User,
  users: Users,
  fileText: FileText,
  barChart: BarChart2,
  bell: Bell,
  menu: Menu,
  close: X,
  sun: Sun,
  moon: Moon,
  language: Languages,
  helpCircle: HelpCircle,
  flag: Flag,
  messageSquare: MessageSquare,
  heart: Heart,
  star: Star,
  arrowUpRight: ArrowUpRight,
  externalLink: ExternalLink,
  copy: Copy,
  edit: Edit,
  plus: Plus,
  minus: Minus,
  filter: Filter,
  sortAsc: SortAsc,
  sortDesc: SortDesc,
  calendar: Calendar,
  clockIcon: ClockIcon,
  mapPinIcon: MapPinIcon,
  shieldCheck: ShieldCheck,
  shieldAlert: ShieldAlert,
  shieldX: ShieldX,
  microscope: Microscope,
  flaskConical: FlaskConical,
  database: Database,
  cloud: Cloud,
  cloudOff: CloudOff,
  wifi: Wifi,
  signal: Signal,
  battery: Battery,
  batteryLow: BatteryLow,
  volume2: Volume2,
  volumeX: VolumeX,
  vibrate: Vibrate,
  vibrateOff: VibrateOff,
  accessibility: Accessibility,
  highlighter: Highlighter,
  type: Type,
  imageIcon: ImageIcon,
  cameraIcon: CameraIcon,
  upload: Upload,
  downloadIcon: DownloadIcon,
  trashIcon: Trash,
  edit2: Edit2,
  save: Save,
  checkCircle2: CheckCircle2,
  xCircle2: XCircle,
  alertTriangleIcon: AlertTriangleIcon,
};

export interface IconProps {
  name: keyof typeof Icons;
  size?: number;
  className?: string;
  'aria-hidden'?: boolean;
}

export function Icon({ name, size = 20, className = '', 'aria-hidden': ariaHidden = true, ...props }: IconProps) {
  const IconComponent = Icons[name];
  if (!IconComponent) {
    console.warn(`Icon "${name}" not found`);
    return null;
  }
  return <IconComponent size={size} className={className} aria-hidden={ariaHidden} {...props} />;
}